import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Card } from "@mui/material";
import MintCard from "../components/Cards/MintCard";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <header>
          <MintCard />
        </header>
      </main>
    </div>
  );
};

export default Home;
